'use strict';
// AUTO-GENERATED by `node server/scripts/analyzeBlockfiles.js --bake`.
// DO NOT HAND-EDIT. Regenerate after re-running the analyzer.
//
// Source: ../data/blockfile-analysis.json
// Generated: 2026-05-03T02:33:14.351Z
// Corpus: 1758 blocks, 635 analytics, 189 cards.
//
// Per-category style shape:
//   1ar_jf           avg 1380 chars / 12.87 sent · 93.3% underline · 26.7% bold · 100% numbered
//   tricks           avg 247 chars / 2.72 sent · 74.6% underline · 3% bold · 94% numbered
//   theory           avg 170 chars / 2.51 sent · 94.2% underline · 10.2% bold · 97.2% numbered
//   k                avg 1252 chars / 8.06 sent · 62% underline · 27.1% bold · 83.7% numbered
//   marlborough_1ar  avg 4315 chars / 27.2 sent · 26.7% underline · 3.3% bold · 73.3% numbered

const CHAT_STYLE_BRIEF = "STYLE — match the conventions of 635 hand-cut analytic chunks across 1,758 blockfiles:\n- Default analytic length: ~622 chars / 5.07 sentences. Single-claim answers can be 1–2 sentences.\n- 93.1% of analytics use a numbered-list shape (1./2./3.) — use it whenever you make multi-part arguments.\n- 82.4% use <u>underline</u> on emphasized phrases. Underline the load-bearing claims; do not underline whole sentences.\n- 12.9% use **bold** for the loudest 1–2 claims of a chunk. Use sparingly.\n- Em-dashes (—) are conventional for offset clauses (~1.02/100 words).\n- ALLCAPS is conventional for transition tokens like REASONABILITY, INNOVATION, NO LINK, NO IMPACT (~1.77/100 words).\n- Lead chunks with a canonical marker when applicable: REASONABILITY, TURN, AT, DEFENSE, LOGIC, FW, CLASH, INNOVATION, NO LINK, NEG FLEX, TIME SKEW, NORMS.\n- Never gloss debate jargon — these are first-class vocabulary: AFF, NEG, 1AR, AT, 1NC, 1AC, FW, CX, 2AR, CP, DA, 2NR, T, CSA, PIC, K, TT, RVI, 2NC, LD.";

const CHAT_FORMATTING_BRIEF = "FORMATTING — corpus-confirmed patterns:\n- Frontline / overview / extension: lead with a CLAIM, then numbered warrants, then the IMPACT.\n- \"AT — X\" responses: open by quoting/naming the opposing claim, then numbered turns/no-links.\n- Cards open blocks (avg position 0.22 from start, 0=open · 1=close) — when citing evidence, place the card first then layer analysis after.\n- Theory analytics are short and punchy (~170 chars); K analytics are long and prosaic (~1,250 chars). Match the user's evident genre.";

const TOP_MARKERS = ["REASONABILITY","TURN","AT","DEFENSE","LOGIC","FW","CLASH","INNOVATION","NO LINK","NEG FLEX","TIME SKEW","NORMS"];

const DEBATE_JARGON = ["AFF","NEG","1AR","AT","1NC","1AC","FW","CX","2AR","CP","DA","2NR","T","CSA","PIC","K","TT","RVI","2NC","LD"];

const CORPUS_META = {
  "blocks": 1758,
  "analytics": 635,
  "cards": 189,
  "generated_at": "2026-05-03T02:33:14.351Z",
  "avg_analytic_chars": 622,
  "avg_analytic_sentences": 5.07,
  "pct_numbered": 93.1,
  "pct_underline": 82.4,
  "pct_bold": 12.9
};

module.exports = {
  CHAT_STYLE_BRIEF,
  CHAT_FORMATTING_BRIEF,
  TOP_MARKERS,
  DEBATE_JARGON,
  CORPUS_META,
};
