'use strict';
// AUTO-GENERATED by `node server/scripts/analyzeBlockfiles.js --bake`.
// DO NOT HAND-EDIT. Regenerate after re-running the analyzer.
//
// Source: ../data/blockfile-analysis.json
// Generated: 2026-05-03T03:59:00.425Z
// Corpus: 1758 blocks, 635 analytics, 189 cards.
//
// Per-category style shape:
//   1ar_jf           avg 1380 chars / 12.87 sent · 93.3% underline · 26.7% bold · 100% numbered
//   tricks           avg 247 chars / 2.72 sent · 74.6% underline · 3% bold · 94% numbered
//   theory           avg 170 chars / 2.51 sent · 94.2% underline · 10.2% bold · 97.2% numbered
//   k                avg 1252 chars / 8.06 sent · 62% underline · 27.1% bold · 83.7% numbered
//   marlborough_1ar  avg 4315 chars / 27.2 sent · 26.7% underline · 3.3% bold · 73.3% numbered

const CHAT_STYLE_BRIEF = "STYLE — chat reply voice (debate-flow, plain prose):\n- Terse, declarative, debate-analytics voice — modeled on 635 hand-cut Vanguard analytics.\n- Default length 1–2 short paragraphs. Match the user's specificity; never pad.\n- Direct answer first, warrant second, impact third. Like a debater on the flow.\n- NO **bold**, NO <u>underline</u>, NO ==highlight==, NO #headings — chat UI shows raw markup chars. Plain text only.\n- NO numbered lists (1. 2. 3.) and NO bullets unless the user explicitly asks for one. Default to prose paragraphs.\n- Separate distinct claims/warrants with a BLANK LINE.\n- Never gloss debate jargon — these are first-class vocabulary, use them as-is: AFF, NEG, 1AR, AT, 1NC, 1AC, FW, CX, 2AR, CP, DA, 2NR, T, CSA, PIC, K, TT, RVI, 2NC, LD.";

const CHAT_FORMATTING_BRIEF = "BLOCK FORMATTING — for /block output (debate document, not chat):\n- 93.1% of corpus analytics use numbered-list shape (1./2./3.) when listing multi-part arguments. Use it for analyticBefore/glueBetween/analyticAfter when listing turns or warrants.\n- 82.4% use <u>underline</u> on emphasized phrases inside analytics — only do this in glue text; cards keep their own preserved markup.\n- 12.9% use **bold** for the loudest 1–2 claims of a chunk. Use sparingly.\n- Em-dashes (—) for offset clauses (~1.02/100 words).\n- ALLCAPS for transition tokens like REASONABILITY, TURN, AT, DEFENSE, LOGIC (~1.77/100 words).\n- Frontline / overview / extension: lead with a CLAIM tag, then card, then 1-sentence implication.\n- \"AT — X\" responses: name the opposing claim, then turns/no-links.\n- Cards open blocks (avg position 0.22 from start, 0=open · 1=close). Place card body first, glue after.\n- DO NOT explain or paraphrase the card body in glue text — the card speaks for itself.";

const TOP_MARKERS = ["REASONABILITY","TURN","AT","DEFENSE","LOGIC","FW","CLASH","INNOVATION","NO LINK","NEG FLEX","TIME SKEW","NORMS"];

const DEBATE_JARGON = ["AFF","NEG","1AR","AT","1NC","1AC","FW","CX","2AR","CP","DA","2NR","T","CSA","PIC","K","TT","RVI","2NC","LD"];

const CORPUS_META = {
  "blocks": 1758,
  "analytics": 635,
  "cards": 189,
  "generated_at": "2026-05-03T03:59:00.425Z",
  "avg_analytic_chars": 622,
  "avg_analytic_sentences": 5.07,
  "pct_numbered": 93.1,
  "pct_underline": 82.4,
  "pct_bold": 12.9
};

module.exports = {
  CHAT_STYLE_BRIEF,
  CHAT_FORMATTING_BRIEF,
  TOP_MARKERS,
  DEBATE_JARGON,
  CORPUS_META,
};
